apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    run: sb-app  
  ports:
    - port: 8080           
      targetPort: 8080      
      nodePort: 30001       
  type: NodePort           
